// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WebScraperML.Model
{
    public class ModelInput
    {
        [ColumnName("IsContainsPrice"), LoadColumn(0)]
        public string IsContainsPrice { get; set; }


        [ColumnName("HtmlElement"), LoadColumn(1)]
        public string HtmlElement { get; set; }


    }
}
